# Generated by Django 5.2.12 on 2026-03-14 19:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0003_chaicertificate_chaireview_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkOrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('org', models.CharField(max_length=150)),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('Classic', 'Classic'), ('Masala', 'Masala'), ('Cold', 'Cold'), ('Special', 'Special')], max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='menu/')),
                ('tag', models.CharField(blank=True, choices=[('', 'None'), ('Bestseller', 'Bestseller'), ('Seasonal', 'Seasonal'), ('New', 'New')], default='', max_length=20)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
            ],
            options={
                'verbose_name': 'Site content',
                'verbose_name_plural': 'Site content',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('quote', models.TextField()),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='chaicertificate',
            options={'ordering': ['-issued_date']},
        ),
        migrations.AlterModelOptions(
            name='chaireview',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterModelOptions(
            name='chaivariety',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['city', 'name']},
        ),
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='store',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='store',
            name='google_maps_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='store',
            name='opening_hours',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='store',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='chaireview',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='store',
            name='chai_varities',
            field=models.ManyToManyField(blank=True, related_name='stores', to='chai.chaivariety'),
        ),
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
